# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f6cd8dad0a5a083d8ccb0870e9cff560401d9c965980bc1a5f66184a5464c72260cb1ba0cb00a04837d0aa567eab3e567198d8aeac0ac37a4703a6f87680ba8

test:
  secret_key_base: 575ee2133b79ac4249b41455fe63eaf9419afa13a1b762c3ce56542169514920525d4883aeee0ce406efd615075f7b2fe7f06b3f274d32db3fb0debbec0a187b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 595bf7e39dca2e5dd91164ee1168dd3c48977692508feda6f7e5df26b007cfa8138bfafd1ec7f3ad0187f066d2aeeafee21fc10953b553a0d0ead579c9df46a4#<%= ENV["SECRET_KEY_BASE"] %>
